# Generated by Django 2.2 on 2019-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfGroup', models.CharField(max_length=250)),
            ],
        ),
    ]
