# Generated by Django 2.2 on 2019-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_groupofusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfCategory', models.CharField(max_length=250)),
            ],
        ),
    ]
