# Generated by Django 2.2 on 2019-06-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=250)),
                ('userPassword', models.CharField(max_length=250)),
                ('groupOfUsersId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GroupOfUsers')),
                ('permissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Permission')),
            ],
        ),
    ]
