# Generated by Django 2.2 on 2019-06-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190602_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='userId',
        ),
        migrations.AlterField(
            model_name='cash',
            name='date',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cash',
            name='money',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
