# Generated by Django 2.2 on 2019-06-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190602_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='userNameId',
        ),
    ]
