# Generated by Django 2.2 on 2019-06-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_order_usernameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='categoryId',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='groupOfUsersId',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='permissionId',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
