# Generated by Django 2.2 on 2019-06-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190603_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='userId',
            field=models.IntegerField(default=1),
        ),
    ]
